import socket
req = input()
# print(req)
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1', 2222))
# s.send(req)
s.send(req.encode('utf-8'))
rsp = s.recv(1024)
print(rsp)
s.close()
